In [1]:
import numpy as np

In [3]:
#numpy array

In [5]:
my_list = [10,20,30,40]

In [7]:
np.array(my_list)

array([10, 20, 30, 40])

In [10]:
my_numpy_array = np.array(my_list)

In [14]:
type(my_numpy_array)

numpy.ndarray

In [16]:
my_numpy_array

array([10, 20, 30, 40])

In [18]:
my_numpy_array[-1]

40

In [22]:
my_numpy_array.max()

40

In [24]:
my_numpy_array[0]=100

In [26]:
my_numpy_array[0]

100

In [30]:
my_numpy_array.max()

100

In [32]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [34]:
matrix_list[0][0]

1

In [38]:
numpy_matrix_list = np.array(matrix_list)

In [40]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [42]:
numpy_matrix_list.shape

(4, 3)

In [44]:
#arange

In [46]:
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [52]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [54]:
#linspace

In [56]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [58]:
#random

In [60]:
np.random.randint(1,100)

39

In [62]:
np.random.randint(1,100,3)

array([68, 54, 59])

In [64]:
#numpy arrays methods

In [68]:
my_numpy_list = np.arange(0,20)
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [70]:
my_numpy_list[4:9:2]

array([4, 6, 8])

In [72]:
my_list=list(range(0,20))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [76]:
my_numpy_list[4:9] =-10
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [80]:
other_list = np.arange(0,15)
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
slicing_list = other_list[4:10]
slicing_list

array([4, 5, 6, 7, 8, 9])

In [86]:
slicing_list[0]

4

In [90]:
slicing_list[:]=100
slicing_list

array([100, 100, 100, 100, 100, 100])

In [92]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [104]:
#numpy referans alınan listeyi de değiştirir

In [106]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [108]:
slicing_my_list = my_list[4:9]

In [110]:
slicing_my_list[0]=-100
slicing_my_list[1]=-100

In [112]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [114]:
#normal listede değiştirilmez

In [116]:
numpy_list_3 = np.arange(0,20)

In [118]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [120]:
numpy_list_3_copy = numpy_list_3.copy()

In [126]:
slicing3 = numpy_list_3_copy[4:9]

In [130]:
slicing3[:]=-100

In [132]:
sliceing3

array([-100, -100, -100, -100, -100])

In [134]:
numpy_list_3_copy

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [136]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [138]:
#ana liste kopyalandığında sadece kopya değişiyor ana liste kalıyor

In [140]:
#numpy operations with numpy arrays

In [142]:
new_array = np.random.randint(1,150,25)

In [144]:
new_array

array([147,  45,  24,  91,  35, 100,  52, 123,   3,  38,  29,  43,   2,
       134, 146,   3,  25,   3,  78, 131,  81, 132,  75,  34,  15])

In [146]:
new_array>50

array([ True, False, False,  True, False,  True,  True,  True, False,
       False, False, False, False,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False])

In [150]:
result_array = new_array>50

In [152]:
result_array

array([ True, False, False,  True, False,  True,  True,  True, False,
       False, False, False, False,  True,  True, False, False, False,
        True,  True,  True,  True,  True, False, False])

In [154]:
new_array[result_array]

array([147,  91, 100,  52, 123, 134, 146,  78, 131,  81, 132,  75])

In [156]:
last_array = np.arange(0,30)
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [158]:
last_array+last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [160]:
last_array.max()

29